####################################################################################################
# Define multiple networks and train them parallel/ in sequence
####################################################################################################

Nbr_processes: 4  # TODO: default ist maximale Anzahl der GPUs
GPU_per_model: 2
Model_run:
  - Model001
  - Model002

Model001:  # TODO: anpassen der Struktur an das neue single_yaml
  Template: flexMLP_single.yaml
  DataLoader:
    create_DataLoader:
      raw_data_path: example_samples.csv
      features: [T_0]
      labels: [T, yCO2]
  Model:
    source: create
    load_model:
      location: None
    create_model:
      n_inp: 1
      n_out: 2
      hidden_layer: [64, 64, 64]
  Trainer:
    max_epochs: 15

Model002:
  Template: flexMLP_single.yaml
  DataLoader:
    raw_data_path: example_samples.csv
    features: [PV]
    labels: [T, yCO2]
  Model:
    source: create
    load_model:
      location: None
    create_model:
      n_inp: 1
      n_out: 2
      hidden_layer: [64, 64]
    params:
      optimizer:
        type: SGD
        params:
          lr: 1.e-3
  Trainer:
    max_epochs: 15