####################################################################################################
# Define multiple networks and train them parallel/ in sequence
####################################################################################################

Nbr_processes: 4
GPU_per_model: 0
#Model_run:
#  - Model001
#  - Model002

Model001:
  Template: input_LightningFlexMLP_single.yaml
  DataLoader:
    create_DataLoader:
      raw_data_path: example_samples.csv
      features: [T_0, PV]
      labels: [T, yCO2]
  Model:
#    load_model:
#      path: None
    create_model:
      n_inp: 2
      n_out: 2
      hidden_layer: [64, 64, 64]
  Trainer:
    params:
      max_epochs: 3
#      profiler: True
    callbacks:
      - type: Checkpointing
        params:
          filepath: checkpoints/try

Model002:
  Template: input_LightningFlexMLP_single.yaml
  DataLoader:
    create_DataLoader:
      raw_data_path: example_samples.csv
      features: [T_0, PV]
      labels: [T, yCO2]
  Model:
#    load_model:
#      path: None
    create_model:
      n_inp: 2
      n_out: 2
      hidden_layer: [64, 64]
    params:
      optimizer:
        type: SGD
        params:
          lr: 1.e-3
  Trainer:
    params:
      max_epochs: 3
#       profiler: True
